### ISSUE TITLE
Test a non-English site

### ISSUE THREAD

**Issue by normanlolx** [leymannx/drupal-circleci-behat#9]
Refs https://github.com/jhedstrom/drupalextension/issues/524

**Comment by esolitos** [comment]
I've been using this on a norwegian based  site, the tricks are:

1. Use the `--locale` option in the site install:
```drush --yes --quiet site:install standard --locale=nb ....```

2. Set the default language's UUID to avoid the error: _"Could not delete the default language"_
```drush --yes --quiet config:set 'language.entity.nb' uuid 'fd9e1640-.....'```

I have encountered some issues with apache, but i believe that this is not related with the language.

**Comment by normanlolx** [comment]
Ah, thanks for sharing.

Additionally we also need to ensure to set the right string in the `behat.yml`. For Foobar language this would be:

```yaml
Drupal\DrupalExtension:
  text:
    log_out: "Foo out"
    log_in: "Foo in"
    password_field: "Foo your bar"
    username_field: "Fooname"
```
